service: food-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    CATEGORIES_TABLE: snackup-${self:provider.stage}-category_table
    FOOD_TABLE: snackup-${self:provider.stage}-food_table
    FOOD_IMAGES_BUCKET: snackup-${self:provider.stage}-food-images-v3
    JWT_SECRET: ${env:JWT_SECRET}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt CategoryTable.Arn
            - !Join ["/", [!GetAtt CategoryTable.Arn, "index/*"]]
            - !GetAtt FoodTable.Arn
            - !Join ["/", [!GetAtt FoodTable.Arn, "index/*"]]

        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::snackup-${self:provider.stage}-food-images-v3/*

  httpApi:
    authorizers:
      adminAuthorizer:
        type: request
        identitySource: $request.header.Authorization
        functionName: authorizer
        payloadFormatVersion: '2.0'
        resultsCacheTtl: 0
        enableSimpleResponses: true
    cors: true

functions:
  authorizer:
    handler: src/shared/authorizer.handler

  createCategory:
    handler: src/modules/category/api/functions/createCategory.handler
    events:
      - httpApi:
          path: /categories
          method: post
          authorizer: adminAuthorizer

  fetchCategories:
    handler: src/modules/category/api/functions/fetchCategories.handler
    events:
      - httpApi:
          path: /categories
          method: get

  fetchCategoryById:
    handler: src/modules/category/api/functions/fetchCategoryById.handler
    events:
      - httpApi:
          path: /categories/{id}
          method: get

  updateCategory:
    handler: src/modules/category/api/functions/updateCategory.handler
    events:
      - httpApi:
          path: /categories/{id}
          method: put
          authorizer: adminAuthorizer

  deleteCategory:
    handler: src/modules/category/api/functions/deleteCategory.handler
    events:
      - httpApi:
          path: /categories/{id}
          method: delete
          authorizer: adminAuthorizer

  uploadFoodImage:
    handler: src/modules/food/api/functions/uploadFoodImage.handler
    events:
      - httpApi:
          path: /foods/upload-url
          method: post
          authorizer: adminAuthorizer

  createFood:
    handler: src/modules/food/api/functions/createFood.handler
    events:
      - httpApi:
          path: /foods
          method: post
          authorizer: adminAuthorizer

  fetchFoodById:
    handler: src/modules/food/api/functions/fetchFoodById.handler
    events:
      - httpApi:
          path: /foods/{id}
          method: get

  updateFood:
    handler: src/modules/food/api/functions/updateFood.handler
    events:
      - httpApi:
          path: /foods/{id}
          method: put
          authorizer: adminAuthorizer

  deleteFood:
    handler: src/modules/food/api/functions/deleteFood.handler
    events:
      - httpApi:
          path: /foods/{id}
          method: delete
          authorizer: adminAuthorizer

  fetchFoodsByCategory:
    handler: src/modules/food/api/functions/fetchFoodsByCategory.handler
    events:
      - httpApi:
          path: /categories/{categoryId}/foods
          method: get
          authorizer: adminAuthorizer

  fetchFoodsMenu:
    handler: src/modules/food/api/functions/fetchFoodsMenu.handler
    events:
      - httpApi:
          path: /menu 
          method: get

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node18
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

resources:
  Resources:

    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CATEGORIES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: categoryName
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CategoryNameIndex
            KeySchema:
              - AttributeName: categoryName
                KeyType: HASH
            Projection:
              ProjectionType: ALL 
        BillingMode: PAY_PER_REQUEST

    FoodTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.FOOD_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: categoryId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
        - IndexName: CategoryIdIndex
          KeySchema:
            - AttributeName: categoryId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

    FoodImagesBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: snackup-${self:provider.stage}-food-images-v3
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
