service: food-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    CATEGORIES_TABLE: snackup-${self:provider.stage}-category_table
    FOOD_TABLE: snackup-${self:provider.stage}-food_table
    JWT_SECRET: ${env:JWT_SECRET}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt CategoryTable.Arn
            - !Join ["/", [!GetAtt CategoryTable.Arn, "index/*"]]
            - !GetAtt FoodTable.Arn
            - !Join ["/", [!GetAtt FoodTable.Arn, "index/*"]]

  httpApi:
    authorizers:
      adminAuthorizer:
        type: request
        identitySource: $request.header.Authorization
        functionName: authorizer
        payloadFormatVersion: '2.0'
        resultsCacheTtl: 0
        enableSimpleResponses: true
    cors: true

functions:
  authorizer:
    handler: src/functions/authorizer.handler
      
  createCategory:
    handler: src/functions/createCategory.handler
    events:
      - httpApi:
          path: /categories
          method: post
          authorizer: adminAuthorizer

  fetchCategories:
    handler: src/functions/fetchCategories.handler
    events:
      - httpApi:
          path: /categories
          method: get

  fetchCategoryById:
    handler: src/functions/fetchCategoryById.handler
    events:
      - httpApi:
          path: /categories/{id}
          method: get

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node18
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

resources:
  Resources:
    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CATEGORIES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: categoryName
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CategoryNameIndex
            KeySchema:
              - AttributeName: categoryName
                KeyType: HASH
            Projection:
              ProjectionType: ALL 
        BillingMode: PAY_PER_REQUEST
        
    FoodTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.FOOD_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
